CREATE TABLE CARS(
	id INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	make VARCHAR(50),
	model VARCHAR(50),
	year_prod INT NOT NULL, 
	type VARCHAR(50),
	price INT,
	specifications VARCHAR(255)
	)